name: Docker CD

on:
  push:
  # branches-ignore:
  #   - "ci-workflow"
  #   - "docker-workflow"
  #  paths:
  #  - "**Dockerfile**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cargo build
      run: |
        cargo build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      run: |
        cargo test

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    #needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: zola # this image-name is changed for the demo
        extract-git-tag: true # Provide flag to extract Docker image tag from git reference
